"use client";

import { useState, useRef, useEffect } from "react";
import { LoadingBars } from "../LoadingBars";
import { FeedbackButton } from "../FeedbackButton";
import { AEO_PURPLE } from "../styles";
import type { DeepAnalysis, ContentSuggestions } from "../../lib/types";

interface AEOTabProps {
  text: string;
  deepAnalysis: DeepAnalysis | null;
  isDeepLoading: boolean;
  publication?: string;
  runDeepAnalysis: () => void;
  aeoContentChanged: boolean;
  contentSuggestions: ContentSuggestions | null;
  isCSLoading: boolean;
  csError: string | null;
  loadContentSuggestions: () => void;
}

const cardStyle: React.CSSProperties = {
  borderRadius: 14,
  background: "rgba(255,255,255,0.55)",
  backdropFilter: "blur(16px) saturate(170%)",
  WebkitBackdropFilter: "blur(16px) saturate(170%)",
  boxShadow: "inset 0 0 0 1px rgba(255,255,255,0.85), inset 1.5px 2px 1px -1px rgba(255,255,255,1), inset -2px -3px 2px -1px rgba(255,255,255,0.6), 0 2px 6px rgba(0,0,0,0.07), 0 10px 26px rgba(0,0,0,0.08)",
  padding: "14px",
};

// Small "AI" pill - inline label marking generative content at the point of generation.
function AiPill() {
  return (
    <span
      style={{
        fontSize: 8.5,
        fontWeight: 700,
        letterSpacing: "0.06em",
        padding: "1px 5px",
        borderRadius: 99,
        background: "rgba(0,0,0,0.06)",
        color: "#4b5563",
        flexShrink: 0,
      }}
      title="Generated by AI - verify before publishing"
    >
      AI
    </span>
  );
}

function SectionHeader({ label, iconColor, ai }: { label: string; iconColor: string; ai?: boolean }) {
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 7, marginBottom: 4 }}>
      <div style={{ width: 7, height: 7, borderRadius: "50%", background: iconColor, flexShrink: 0 }} />
      <span style={{ fontSize: 10.5, textTransform: "uppercase", letterSpacing: "0.06em", color: "#4b5563", fontWeight: 600, flex: 1 }}>
        {label}
      </span>
      {ai && <AiPill />}
    </div>
  );
}

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);
  const copyTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  useEffect(() => { return () => { if (copyTimerRef.current) clearTimeout(copyTimerRef.current); }; }, []);
  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      if (copyTimerRef.current) clearTimeout(copyTimerRef.current);
      copyTimerRef.current = setTimeout(() => setCopied(false), 1500);
    } catch {
      // silent
    }
  };
  return (
    <button
      onClick={handleCopy}
      style={{
        background: "none", border: "none", cursor: "pointer", padding: 2,
        display: "flex", alignItems: "center", gap: 3,
        color: copied ? "#16a34a" : "#9ca3af", fontSize: 10, fontWeight: 600, flexShrink: 0,
        transition: "color 150ms",
      }}
      title={copied ? "Copied!" : "Copy to clipboard"}
    >
      {copied ? (
        <svg width="11" height="11" viewBox="0 0 20 20" fill="currentColor">
          <path fillRule="evenodd" d="M16.704 4.153a.75.75 0 01.143 1.052l-8 10.5a.75.75 0 01-1.127.075l-4.5-4.5a.75.75 0 011.06-1.06l3.894 3.893 7.48-9.817a.75.75 0 011.05-.143z" clipRule="evenodd" />
        </svg>
      ) : (
        <svg width="11" height="11" viewBox="0 0 20 20" fill="currentColor">
          <path d="M7 3.5A1.5 1.5 0 018.5 2h3.879a1.5 1.5 0 011.06.44l3.122 3.12A1.5 1.5 0 0117 6.622V12.5a1.5 1.5 0 01-1.5 1.5h-1v-3.379a3 3 0 00-.879-2.121L10.5 5.379A3 3 0 008.379 4.5H7v-1z" />
          <path d="M4.5 6A1.5 1.5 0 003 7.5v9A1.5 1.5 0 004.5 18h7a1.5 1.5 0 001.5-1.5v-5.879a1.5 1.5 0 00-.44-1.06L9.44 6.439A1.5 1.5 0 008.378 6H4.5z" />
        </svg>
      )}
    </button>
  );
}

export function AEOTab({
  text, deepAnalysis, isDeepLoading, publication, runDeepAnalysis, aeoContentChanged,
  contentSuggestions, isCSLoading, csError, loadContentSuggestions,
}: AEOTabProps) {

  if (!deepAnalysis && isDeepLoading) {
    return (
      <div style={{ padding: 24, display: "flex", alignItems: "center", justifyContent: "center", gap: 8 }}>
        <LoadingBars size="xs" color={AEO_PURPLE} />
        <span style={{ fontSize: 12, color: "#4b5563" }}>Generating AEO insights...</span>
      </div>
    );
  }

  if (!deepAnalysis) {
    return (
      <div style={{ padding: 24, textAlign: "center" }}>
        <div style={{ fontSize: 13, color: "#4b5563", fontWeight: 500 }}>AEO data not available yet</div>
        <div style={{ fontSize: 11, color: "#6b7280", marginTop: 4 }}>Start writing in the document to begin</div>
      </div>
    );
  }

  const aeo = deepAnalysis.aeo;
  const questionHeadings =
    aeo?.questionHeadings?.map((qh) => ({
      heading: qh.suggestedHeading, originalHeading: qh.originalHeading, rationale: qh.rationale,
    })) ??
    aeo?.headingSuggestions?.map((h) => ({
      heading: h.heading, originalHeading: undefined as string | undefined, rationale: h.rationale,
    })) ?? [];

  return (
    <div style={{ padding: 12, display: "flex", flexDirection: "column", gap: 12 }}>
      {/* The AI-generated disclaimer lives at the panel level (above the tab bar)
          so every tab inherits it - no per-tab repetition. */}

      {/* The "Keep it fresh" / Updated-on notice now lives at the top of the Meta tab. */}

      {aeoContentChanged && (
        <div onClick={runDeepAnalysis} style={{
          padding: "8px 12px", background: "#fffbeb", border: "1px solid #fde68a", borderRadius: 8,
          display: "flex", alignItems: "center", justifyContent: "space-between", cursor: "pointer",
        }} role="button" tabIndex={0} onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); runDeepAnalysis(); } }}>
          <span style={{ fontSize: 11, color: "#92400e" }}>Content has changed since this was generated.</span>
          <span style={{ fontSize: 11, fontWeight: 600, color: AEO_PURPLE, textDecoration: "underline" }}>Update</span>
        </div>
      )}

      {!aeo && (
        <div style={{ ...cardStyle, textAlign: "center" }}>
          <span style={{ fontSize: 12, color: "#4b5563" }}>
            No insights came back. Try again - the analysis may have timed out.
          </span>
        </div>
      )}

      {questionHeadings.length > 0 && (
        <div style={cardStyle}>
          <SectionHeader label="Question-Style Headings" iconColor={AEO_PURPLE} />
          <div style={{ fontSize: 10, color: "#4b5563", marginBottom: 8 }}>
            Rewrites of your existing headings as questions. Google often pulls these into featured snippets.
          </div>
          <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
            {questionHeadings.map((h, i) => (
              <div key={i} style={{
                padding: "8px 10px", background: "rgba(0,93,172,0.03)",
                borderRadius: 10, borderLeft: `3px solid ${AEO_PURPLE}`,
              }}>
                <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 8 }}>
                  <div style={{ flex: 1 }}>
                    {h.originalHeading && (
                      <div style={{ fontSize: 11, color: "#4b5563", textDecoration: "line-through", marginBottom: 2 }}>
                        {h.originalHeading}
                      </div>
                    )}
                    <div style={{ fontSize: 12, fontWeight: 700, color: AEO_PURPLE, lineHeight: 1.5 }}>{h.heading}</div>
                  </div>
                  <div style={{ display: "flex", alignItems: "center", gap: 4 }}>
                    <CopyButton text={h.heading} />
                    <FeedbackButton suggestionType="aeo_heading" suggestionText={h.heading} publication={publication} />
                  </div>
                </div>
                <div style={{ fontSize: 10, color: "#4b5563", marginTop: 4, fontStyle: "italic" }}>{h.rationale}</div>
              </div>
            ))}
          </div>
        </div>
      )}

      <div style={cardStyle}>
        <SectionHeader label="Content Block Suggestions" iconColor={AEO_PURPLE} />
        <div style={{ fontSize: 10, color: "#4b5563", marginBottom: 10 }}>
          Short, citable blocks to use inside or alongside the article - takeaways, infographic ideas, and bullet points.
        </div>

        {!contentSuggestions && !isCSLoading && (
          <button
            onClick={loadContentSuggestions}
            disabled={!text || text.trim().length < 100}
            style={{
              width: "100%", padding: "8px 12px", fontSize: 11, fontWeight: 600,
              color: !text || text.trim().length < 100 ? "#9ca3af" : "#ffffff",
              background: !text || text.trim().length < 100 ? "#e5e7eb" : AEO_PURPLE,
              border: "none", borderRadius: 6,
              cursor: !text || text.trim().length < 100 ? "not-allowed" : "pointer",
              display: "flex", alignItems: "center", justifyContent: "center", gap: 6, transition: "all 150ms",
            }}
          >
            Generate suggestions
          </button>
        )}

        {isCSLoading && (
          <div style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: 8, padding: "8px 0" }}>
            <LoadingBars size="xs" color={AEO_PURPLE} />
            <span style={{ fontSize: 11, color: "#4b5563" }}>Generating content suggestions...</span>
          </div>
        )}

        {csError && <div style={{ marginTop: 6, fontSize: 11, color: "#dc2626" }}>{csError}</div>}

        {contentSuggestions && (
          <div style={{ display: "flex", flexDirection: "column", gap: 14, marginTop: 8 }}>
            {contentSuggestions.keyTakeaways.length > 0 && (
              <div>
                <div style={{ fontSize: 10, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.06em", color: AEO_PURPLE, marginBottom: 6 }}>
                  Key Takeaways
                </div>
                <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
                  {contentSuggestions.keyTakeaways.map((kt, i) => (
                    <div key={i} style={{
                      padding: "6px 10px", background: "rgba(0,93,172,0.03)",
                      borderRadius: 8, borderLeft: `2px solid ${AEO_PURPLE}`,
                      display: "flex", gap: 8, alignItems: "flex-start",
                    }}>
                      <span style={{ fontSize: 12, color: "#1f2937", lineHeight: 1.55, flex: 1 }}>{kt}</span>
                      <div style={{ display: "flex", alignItems: "center", gap: 4 }}>
                        <CopyButton text={kt} />
                        <FeedbackButton suggestionType="aeo_takeaway" suggestionText={kt} publication={publication} />
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {contentSuggestions.infographicOpportunities.length > 0 && (
              <div>
                <div style={{ fontSize: 10, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.06em", color: AEO_PURPLE, marginBottom: 6 }}>
                  Infographic Ideas
                </div>
                <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
                  {contentSuggestions.infographicOpportunities.map((io, i) => (
                    <div key={i} style={{
                      padding: "8px 10px", background: "rgba(0,93,172,0.03)",
                      borderRadius: 8, borderLeft: `2px solid ${AEO_PURPLE}`,
                    }}>
                      <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 8 }}>
                        <span style={{ fontSize: 12, fontWeight: 700, color: AEO_PURPLE }}>{io.concept}</span>
                        <FeedbackButton suggestionType="aeo_infographic" suggestionText={io.concept} publication={publication} />
                      </div>
                      <div style={{ fontSize: 11, color: "#1f2937", lineHeight: 1.5, marginTop: 3 }}>{io.description}</div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {contentSuggestions.bulletListItems.length > 0 && (
              <div>
                <div style={{ fontSize: 10, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.06em", color: AEO_PURPLE, marginBottom: 6 }}>
                  Bullets for Featured Snippets
                </div>
                <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 8 }}>
                  <ul style={{ margin: 0, paddingLeft: 18, flex: 1 }}>
                    {contentSuggestions.bulletListItems.map((b, i) => (
                      <li key={i} style={{ fontSize: 12, color: "#1f2937", lineHeight: 1.55, marginBottom: 4 }}>{b}</li>
                    ))}
                  </ul>
                  <div style={{ display: "flex", alignItems: "center", gap: 4 }}>
                    <CopyButton text={contentSuggestions.bulletListItems.map((b) => "- " + b).join("\n")} />
                    <FeedbackButton
                      suggestionType="aeo_bullets"
                      suggestionText={contentSuggestions.bulletListItems.join(" | ")}
                      publication={publication}
                    />
                  </div>
                </div>
              </div>
            )}

            <button
              onClick={loadContentSuggestions}
              disabled={isCSLoading}
              style={{
                marginTop: 4, padding: "6px 12px", fontSize: 11, fontWeight: 600,
                color: AEO_PURPLE, background: "rgba(0,93,172,0.06)",
                border: "1px solid rgba(0,93,172,0.15)", borderRadius: 6,
                cursor: isCSLoading ? "wait" : "pointer",
                display: "flex", alignItems: "center", justifyContent: "center", gap: 6,
              }}
            >
              Regenerate
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
