"use client";

import { LoadingBars } from "../LoadingBars";
import { FeedbackButton } from "../FeedbackButton";
import { ScoreDonut, ScoreDonutLegend } from "../ScoreDonut";
import { MJH_BLUE } from "../styles";
import type { SEOAnalysis, LinkingSuggestion } from "../../lib/types";

interface LinkingTabProps {
  analysis: SEOAnalysis | null;
  suggestions: LinkingSuggestion[];
  isLoading: boolean;
  error?: string | null;
  /** True when the article changed materially since these suggestions were fetched. */
  isStale?: boolean;
  onRefresh: () => void;
  text?: string;
  documentId?: string;
  publication?: string;
}

const cardStyle: React.CSSProperties = {
  borderRadius: 14,
  background: "#ffffff",
  boxShadow: "0 1px 3px rgba(0,0,0,0.04), 0 0 0 1px rgba(0,0,0,0.03)",
  padding: "14px",
};

// Small "AI" pill - inline label marking generative content at the point of generation.
function AiPill() {
  return (
    <span
      style={{
        fontSize: 8.5,
        fontWeight: 700,
        letterSpacing: "0.06em",
        padding: "1px 5px",
        borderRadius: 99,
        background: "rgba(0,0,0,0.06)",
        color: "#6b7280",
        flexShrink: 0,
      }}
      title="Generated by AI - verify before publishing"
    >
      AI
    </span>
  );
}

function SectionHeader({
  label,
  iconColor,
  ai,
  action,
}: {
  label: string;
  iconColor: string;
  ai?: boolean;
  action?: React.ReactNode;
}) {
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 7, marginBottom: 8 }}>
      <div style={{ width: 7, height: 7, borderRadius: "50%", background: iconColor, flexShrink: 0 }} />
      <span style={{ fontSize: 10.5, textTransform: "uppercase", letterSpacing: "0.06em", color: "#94a3b8", fontWeight: 600, flex: 1 }}>
        {label}
      </span>
      {ai && <AiPill />}
      {action}
    </div>
  );
}

function formatDate(iso?: string): string {
  if (!iso) return "";
  try {
    return new Date(iso).toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" });
  } catch {
    return "";
  }
}

function freshnessChip(label: LinkingSuggestion["freshnessLabel"], score: number) {
  const map = {
    fresh: { bg: "rgba(22,163,74,0.1)", color: "#16a34a", text: "Fresh" },
    recent: { bg: "rgba(0,93,172,0.08)", color: MJH_BLUE, text: "Recent" },
    older: { bg: "rgba(230,192,27,0.18)", color: "#8B7310", text: "Older" },
    "very-old": { bg: "rgba(220,38,38,0.1)", color: "#dc2626", text: "Very old" },
  } as const;
  const c = map[label];
  return (
    <span
      style={{
        fontSize: 9,
        fontWeight: 700,
        textTransform: "uppercase",
        letterSpacing: "0.05em",
        padding: "1px 6px",
        borderRadius: 99,
        background: c.bg,
        color: c.color,
        flexShrink: 0,
      }}
      title={`Freshness score: ${score}/100`}
    >
      {c.text}
    </span>
  );
}

function RefreshIcon({ spinning }: { spinning: boolean }) {
  if (spinning) return <LoadingBars size="xs" color="#9ca3af" />;
  return (
    <svg width="12" height="12" viewBox="0 0 20 20" fill="currentColor">
      <path fillRule="evenodd" d="M15.312 11.424a5.5 5.5 0 01-9.201 2.466l-.312-.311h2.433a.75.75 0 000-1.5H4.598a.75.75 0 00-.75.75v3.634a.75.75 0 001.5 0v-2.033l.312.311a7 7 0 0011.712-3.138.75.75 0 00-1.449-.39zm-10.624-2.85a5.5 5.5 0 019.201-2.466l.312.311h-2.433a.75.75 0 000 1.5h3.634a.75.75 0 00.75-.75V3.535a.75.75 0 00-1.5 0v2.033l-.312-.311A7 7 0 002.628 8.395a.75.75 0 001.449.39z" clipRule="evenodd" />
    </svg>
  );
}

export function LinkingTab({
  analysis,
  suggestions,
  isLoading,
  error,
  isStale,
  onRefresh,
  text,
  documentId,
  publication,
}: LinkingTabProps) {
  if (!analysis) {
    return (
      <div style={{ padding: 24, textAlign: "center" }}>
        <div style={{ fontSize: 13, color: "#9ca3af", fontWeight: 500 }}>Run keyword analysis first</div>
        <div style={{ fontSize: 11, color: "#d1d5db", marginTop: 4 }}>Internal link suggestions need keywords to start from</div>
      </div>
    );
  }

  // Linking strategy guidance - 2026 research: 2-5 contextual links per 1,000 words for hub-and-spoke
  const wordCount = text ? text.split(/\s+/).filter(Boolean).length : 0;
  const recommendedMin = Math.max(1, Math.round((wordCount / 1000) * 2));
  const recommendedMax = Math.max(2, Math.round((wordCount / 1000) * 5));

  return (
    <div style={{ padding: 12, display: "flex", flexDirection: "column", gap: 12 }}>
      {/* Linking Strategy Guidance */}
      <div style={cardStyle}>
        <SectionHeader label="Hub-and-Spoke Strategy" iconColor={MJH_BLUE} />
        <div style={{ fontSize: 11, color: "#4b5563", lineHeight: 1.55 }}>
          Link to <strong>prior research, past coverage, and interviews</strong> on the same topic. Sites with systematic topic-cluster linking moved from ~12% to ~41% AI citation rate for pillar topics.
        </div>
        {wordCount > 0 && (
          <div
            style={{
              marginTop: 10,
              padding: "8px 10px",
              background: "rgba(0,93,172,0.04)",
              borderLeft: `2px solid ${MJH_BLUE}`,
              borderRadius: 6,
              fontSize: 11,
              color: "#1e293b",
              lineHeight: 1.5,
            }}
          >
            For your {wordCount.toLocaleString()}-word article, aim for <strong>{recommendedMin}-{recommendedMax} contextual links</strong> (2-5 per 1,000 words). Keep total page links under 150 to avoid equity dilution.
          </div>
        )}
      </div>

      <div id="anchor-linking-suggestions" style={cardStyle}>
        <SectionHeader
          label="Topic-Scored Suggestions"
          iconColor={MJH_BLUE}
          ai
          action={
            <button
              onClick={onRefresh}
              disabled={isLoading}
              style={{
                background: "none",
                border: "none",
                cursor: isLoading ? "wait" : "pointer",
                padding: 2,
                display: "flex",
                color: isLoading ? "#d1d5db" : "#9ca3af",
                fontSize: 10,
              }}
              title="Refresh"
            >
              <RefreshIcon spinning={isLoading} />
            </button>
          }
        />
        <div style={{ fontSize: 10, color: "#9ca3af", marginBottom: 6, lineHeight: 1.5 }}>
          The donut shows how each factor contributed: topic match, freshness (12-month half-life), and how well a specific paragraph in your article hosts the link. Hover it for the raw sub-scores.
        </div>
        <div style={{ marginBottom: 10 }}>
          <ScoreDonutLegend />
        </div>

        {/* Stale banner - article changed since these were generated */}
        {isStale && suggestions.length > 0 && !isLoading && (
          <div
            onClick={onRefresh}
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
              gap: 8,
              padding: "7px 10px",
              marginBottom: 10,
              background: "#fffbeb",
              border: "1px solid #fde68a",
              borderRadius: 8,
              cursor: "pointer",
            }}
          >
            <span style={{ fontSize: 11, color: "#92400e" }}>
              Your article changed since these were generated.
            </span>
            <span style={{ fontSize: 11, fontWeight: 700, color: "#8B7310", textDecoration: "underline", flexShrink: 0 }}>
              Refresh
            </span>
          </div>
        )}

        {/* Loading (first run, nothing to show yet) */}
        {isLoading && suggestions.length === 0 && (
          <div style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: 8, padding: "16px 0" }}>
            <LoadingBars size="xs" color={MJH_BLUE} />
            <span style={{ fontSize: 11, color: "#9ca3af" }}>Ranking candidates...</span>
          </div>
        )}

        {/* Error - distinct from "empty", with a real retry affordance */}
        {!isLoading && error && (
          <div
            style={{
              padding: "12px",
              background: "rgba(220,38,38,0.04)",
              border: "1px solid rgba(220,38,38,0.18)",
              borderRadius: 10,
              textAlign: "center",
            }}
          >
            <div style={{ fontSize: 11.5, color: "#b91c1c", fontWeight: 600, marginBottom: 2 }}>
              Couldn't load suggestions
            </div>
            <div style={{ fontSize: 10.5, color: "#9ca3af", marginBottom: 8 }}>{error}</div>
            <button
              onClick={onRefresh}
              style={{
                padding: "5px 14px",
                fontSize: 11,
                fontWeight: 700,
                color: "#ffffff",
                background: "#dc2626",
                border: "none",
                borderRadius: 6,
                cursor: "pointer",
              }}
            >
              Try again
            </button>
          </div>
        )}

        {/* Empty - no error, just nothing matched. Points to the fix, no retry. */}
        {!isLoading && !error && suggestions.length === 0 && (
          <div style={{ fontSize: 11, color: "#9ca3af", textAlign: "center", padding: "12px 0", lineHeight: 1.5 }}>
            No related articles found.
            <br />
            Try broadening or adjusting your keywords in the Keywords tab.
          </div>
        )}

        {suggestions.length > 0 && (
          <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
            {suggestions.map((s) => (
              <div
                key={s._id}
                style={{
                  padding: "10px 12px",
                  background: "rgba(0,93,172,0.03)",
                  borderRadius: 10,
                  borderLeft: `2px solid ${MJH_BLUE}`,
                  display: "flex",
                  gap: 12,
                  alignItems: "flex-start",
                }}
              >
                <ScoreDonut
                  size={64}
                  topic={s.topicScore}
                  freshness={s.freshnessScore}
                  sectionFit={s.sectionFitScore}
                  composite={s.compositeScore}
                />
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 3, flexWrap: "wrap" }}>
                    {freshnessChip(s.freshnessLabel, s.freshnessScore)}
                    {s.publishedAt && (
                      <span style={{ fontSize: 10, color: "#9ca3af" }}>{formatDate(s.publishedAt)}</span>
                    )}
                  </div>
                  <div style={{ fontSize: 12, fontWeight: 700, color: "#1f2937", lineHeight: 1.4, marginBottom: 2 }}>
                    {s.title}
                  </div>
                  <div style={{ fontSize: 10, color: "#9ca3af", fontFamily: "ui-monospace, SFMono-Regular, monospace", marginBottom: 6 }}>
                    /{s.slug}
                  </div>
                  {s.relevanceReason && (
                    <div style={{ fontSize: 11, color: "#475569", marginBottom: 6, lineHeight: 1.45 }}>
                      <span style={{ fontWeight: 700, color: "#94a3b8" }}>AI matched this because:</span>{" "}
                      <span style={{ fontStyle: "italic" }}>{s.relevanceReason}</span>
                    </div>
                  )}
                  {s.anchorQuote && (
                    <div
                      style={{
                        marginTop: 4,
                        padding: "6px 9px",
                        background: "rgba(0,0,0,0.025)",
                        borderRadius: 6,
                        borderLeft: "2px solid #cbd5e1",
                        fontSize: 11,
                        color: "#374151",
                        lineHeight: 1.5,
                      }}
                    >
                      <div style={{ fontSize: 9, fontWeight: 700, color: "#94a3b8", textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: 3 }}>
                        Fit here (paragraph {s.anchorParagraph})
                      </div>
                      <div style={{ fontStyle: "italic" }}>"{s.anchorQuote}"</div>
                      {s.anchorReason && (
                        <div style={{ fontSize: 10, color: "#9ca3af", marginTop: 3, lineHeight: 1.45 }}>
                          {s.anchorReason}
                        </div>
                      )}
                    </div>
                  )}
                </div>
                <div style={{ flexShrink: 0 }}>
                  <FeedbackButton
                    suggestionType="internal_link"
                    suggestionText={s.title}
                    publication={publication}
                    documentId={documentId}
                  />
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
