"use client";

import { LoadingBars } from "../LoadingBars";
import { FeedbackButton } from "../FeedbackButton";
import { ScoreDonut, ScoreDonutLegend } from "../ScoreDonut";
import { MJH_BLUE } from "../styles";
import type { SEOAnalysis, LinkingSuggestion } from "../../lib/types";
import { KNOWN_MJH_PUBLICATIONS } from "../../lib/utils";

interface LinkingTabProps {
  analysis: SEOAnalysis | null;
  suggestions: LinkingSuggestion[];
  isLoading: boolean;
  error?: string | null;
  /** True when the article changed materially since these suggestions were fetched. */
  isStale?: boolean;
  onRefresh: () => void;
  text?: string;
  documentId?: string;
  publication?: string;
}

// Build the public, reader-facing URL for a suggested article. Only constructed for
// known MJH publications (verified via CDN probe to use www.{pub}.com/view/{slug}).
// Returns null for unknown publications rather than risking a broken link.
function buildLiveUrl(publication?: string, slug?: string): string | null {
  if (!slug) return null;
  const pub = (publication || "").trim().toLowerCase();
  if (!KNOWN_MJH_PUBLICATIONS.has(pub)) return null;
  const cleanSlug = slug.replace(/^\/+/, "").split("/").map(encodeURIComponent).join("/");
  return `https://www.${pub}.com/view/${cleanSlug}`;
}

// Clickable chip that opens a URL in a new tab.
function LinkChip({ href, label, color }: { href: string; label: string; color: string }) {
  return (
    <a
      href={href}
      target="_blank"
      rel="noopener noreferrer"
      style={{
        display: "inline-flex",
        alignItems: "center",
        gap: 4,
        padding: "3px 9px",
        borderRadius: 99,
        fontSize: 10.5,
        fontWeight: 700,
        color,
        background: "rgba(255,255,255,0.7)",
        border: `1px solid ${color}33`,
        textDecoration: "none",
        lineHeight: 1.2,
      }}
    >
      {label}
      <svg width="9" height="9" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
        <path d="M12.5 2a.75.75 0 000 1.5h2.44l-6.97 6.97a.75.75 0 101.06 1.06L16 4.56V7a.75.75 0 001.5 0V2.75A.75.75 0 0016.75 2H12.5z" />
        <path d="M4.75 4.5A2.75 2.75 0 002 7.25v8A2.75 2.75 0 004.75 18h8A2.75 2.75 0 0015.5 15.25v-3a.75.75 0 00-1.5 0v3c0 .69-.56 1.25-1.25 1.25h-8c-.69 0-1.25-.56-1.25-1.25v-8c0-.69.56-1.25 1.25-1.25h3a.75.75 0 000-1.5h-3z" />
      </svg>
    </a>
  );
}

const cardStyle: React.CSSProperties = {
  borderRadius: 14,
  background: "rgba(255,255,255,0.55)",
  backdropFilter: "blur(16px) saturate(170%)",
  WebkitBackdropFilter: "blur(16px) saturate(170%)",
  boxShadow: "inset 0 0 0 1px rgba(255,255,255,0.85), inset 1.5px 2px 1px -1px rgba(255,255,255,1), inset -2px -3px 2px -1px rgba(255,255,255,0.6), 0 2px 6px rgba(0,0,0,0.07), 0 10px 26px rgba(0,0,0,0.08)",
  padding: "14px",
};

// Small "AI" pill - inline label marking generative content at the point of generation.
function AiPill() {
  return (
    <span
      style={{
        fontSize: 8.5,
        fontWeight: 700,
        letterSpacing: "0.06em",
        padding: "1px 5px",
        borderRadius: 99,
        background: "rgba(0,0,0,0.06)",
        color: "#4b5563",
        flexShrink: 0,
      }}
      title="Generated by AI - verify before publishing"
    >
      AI
    </span>
  );
}

function SectionHeader({
  label,
  iconColor,
  ai,
  action,
}: {
  label: string;
  iconColor: string;
  ai?: boolean;
  action?: React.ReactNode;
}) {
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 7, marginBottom: 8 }}>
      <div style={{ width: 7, height: 7, borderRadius: "50%", background: iconColor, flexShrink: 0 }} />
      <span style={{ fontSize: 10.5, textTransform: "uppercase", letterSpacing: "0.06em", color: "#4b5563", fontWeight: 600, flex: 1 }}>
        {label}
      </span>
      {ai && <AiPill />}
      {action}
    </div>
  );
}

function formatDate(iso?: string): string {
  if (!iso) return "";
  try {
    return new Date(iso).toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" });
  } catch {
    return "";
  }
}

function freshnessChip(label: LinkingSuggestion["freshnessLabel"], score: number) {
  const map = {
    fresh: { bg: "rgba(22,163,74,0.1)", color: "#16a34a", text: "Fresh" },
    recent: { bg: "rgba(0,93,172,0.08)", color: MJH_BLUE, text: "Recent" },
    older: { bg: "rgba(230,192,27,0.18)", color: "#8B7310", text: "Older" },
    "very-old": { bg: "rgba(220,38,38,0.1)", color: "#dc2626", text: "Very old" },
  } as const;
  const c = map[label];
  return (
    <span
      style={{
        fontSize: 9,
        fontWeight: 700,
        textTransform: "uppercase",
        letterSpacing: "0.05em",
        padding: "1px 6px",
        borderRadius: 99,
        background: c.bg,
        color: c.color,
        flexShrink: 0,
      }}
      title={`Freshness score: ${score}/100`}
    >
      {c.text}
    </span>
  );
}

function RefreshIcon({ spinning }: { spinning: boolean }) {
  if (spinning) return <LoadingBars size="xs" color="#9ca3af" />;
  return (
    <svg width="12" height="12" viewBox="0 0 20 20" fill="currentColor">
      <path fillRule="evenodd" d="M15.312 11.424a5.5 5.5 0 01-9.201 2.466l-.312-.311h2.433a.75.75 0 000-1.5H4.598a.75.75 0 00-.75.75v3.634a.75.75 0 001.5 0v-2.033l.312.311a7 7 0 0011.712-3.138.75.75 0 00-1.449-.39zm-10.624-2.85a5.5 5.5 0 019.201-2.466l.312.311h-2.433a.75.75 0 000 1.5h3.634a.75.75 0 00.75-.75V3.535a.75.75 0 00-1.5 0v2.033l-.312-.311A7 7 0 002.628 8.395a.75.75 0 001.449.39z" clipRule="evenodd" />
    </svg>
  );
}

export function LinkingTab({
  analysis,
  suggestions,
  isLoading,
  error,
  isStale,
  onRefresh,
  text,
  documentId,
  publication,
}: LinkingTabProps) {
  if (!analysis) {
    return (
      <div style={{ padding: 24, textAlign: "center" }}>
        <div style={{ fontSize: 13, color: "#4b5563", fontWeight: 500 }}>Waiting for keyword analysis</div>
        <div style={{ fontSize: 11, color: "#4b5563", marginTop: 4 }}>Linking reads the article keywords and topic to find related published articles. It starts on its own once the Keywords tab finishes.</div>
      </div>
    );
  }

  // Healthy contextual link counts scale with article length (roughly 2-5 per 1,000 words).
  const wordCount = text ? text.split(/\s+/).filter(Boolean).length : 0;
  const recommendedMin = Math.max(1, Math.round((wordCount / 1000) * 2));
  const recommendedMax = Math.max(2, Math.round((wordCount / 1000) * 5));

  return (
    <div style={{ padding: 12, display: "flex", flexDirection: "column", gap: 12 }}>
      <div id="anchor-linking-suggestions" style={cardStyle}>
        <SectionHeader
          label="Suggested Links"
          iconColor={MJH_BLUE}
          action={
            <button
              onClick={onRefresh}
              disabled={isLoading}
              style={{
                background: "none",
                border: "none",
                cursor: isLoading ? "wait" : "pointer",
                padding: 2,
                display: "flex",
                color: isLoading ? "#d1d5db" : "#9ca3af",
                fontSize: 10,
              }}
              title="Refresh"
            >
              <RefreshIcon spinning={isLoading} />
            </button>
          }
        />
        <div style={{ fontSize: 11, color: "#1f2937", marginBottom: 8, lineHeight: 1.55 }}>
          Other articles on this site that fit the topic.
          {wordCount > 0 && (
            <>
              {" "}For a {wordCount.toLocaleString()}-word article, aim for{" "}
              <strong>{recommendedMin}-{recommendedMax} internal links</strong>.
            </>
          )}
        </div>
        <div style={{ fontSize: 10, color: "#4b5563", marginBottom: 6, lineHeight: 1.5 }}>
          Each suggestion gets a 0-100% match score from three signals - <strong>topic match</strong>, <strong>freshness</strong>, and <strong>section fit</strong> (where in your article the link belongs). The percentage on each card is the weighted total:
        </div>
        <div style={{ marginBottom: 10 }}>
          <ScoreDonutLegend />
        </div>

        {/* Stale banner - article changed since these were generated */}
        {isStale && suggestions.length > 0 && !isLoading && (
          <div
            onClick={onRefresh}
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
              gap: 8,
              padding: "7px 10px",
              marginBottom: 10,
              background: "#fffbeb",
              border: "1px solid #fde68a",
              borderRadius: 8,
              cursor: "pointer",
            }}
          >
            <span style={{ fontSize: 11, color: "#92400e" }}>
              Your article changed since these were generated.
            </span>
            <span style={{ fontSize: 11, fontWeight: 700, color: "#8B7310", textDecoration: "underline", flexShrink: 0 }}>
              Refresh
            </span>
          </div>
        )}

        {/* Loading (first run, nothing to show yet) */}
        {isLoading && suggestions.length === 0 && (
          <div style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: 8, padding: "16px 0" }}>
            <LoadingBars size="xs" color={MJH_BLUE} />
            <span style={{ fontSize: 11, color: "#4b5563" }}>Ranking candidates...</span>
          </div>
        )}

        {/* Error - distinct from "empty", with a real retry affordance */}
        {!isLoading && error && (
          <div
            style={{
              padding: "12px",
              background: "rgba(220,38,38,0.04)",
              border: "1px solid rgba(220,38,38,0.18)",
              borderRadius: 10,
              textAlign: "center",
            }}
          >
            <div style={{ fontSize: 11.5, color: "#b91c1c", fontWeight: 600, marginBottom: 2 }}>
              Couldn't load suggestions
            </div>
            <div style={{ fontSize: 10.5, color: "#4b5563", marginBottom: 8 }}>{error}</div>
            <button
              onClick={onRefresh}
              style={{
                padding: "5px 14px",
                fontSize: 11,
                fontWeight: 700,
                color: "#ffffff",
                background: "#dc2626",
                border: "none",
                borderRadius: 6,
                cursor: "pointer",
              }}
            >
              Try again
            </button>
          </div>
        )}

        {/* Empty - no error, just nothing matched. */}
        {!isLoading && !error && suggestions.length === 0 && (
          <div style={{ fontSize: 11, color: "#1f2937", padding: "10px 12px", lineHeight: 1.55, background: "rgba(0,93,172,0.04)", borderRadius: 8, border: "1px solid rgba(0,93,172,0.12)" }}>
            <div style={{ fontWeight: 700, marginBottom: 4, color: "#1f2937" }}>No closely related articles found.</div>
            <div style={{ color: "#4b5563" }}>
              Linking searched your publication for articles on this topic and did not find a strong match. As more related content is published, suggestions will appear here.
            </div>
          </div>
        )}

        {suggestions.length > 0 && (
          <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
            {suggestions.map((s) => (
              <div
                key={s._id}
                style={{
                  padding: "10px 12px",
                  background: "rgba(0,93,172,0.03)",
                  borderRadius: 10,
                  borderLeft: `2px solid ${MJH_BLUE}`,
                  display: "flex",
                  gap: 12,
                  alignItems: "flex-start",
                }}
              >
                <ScoreDonut
                  size={64}
                  topic={s.topicScore}
                  freshness={s.freshnessScore}
                  sectionFit={s.sectionFitScore}
                  composite={s.compositeScore}
                />
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 3, flexWrap: "wrap" }}>
                    {freshnessChip(s.freshnessLabel, s.freshnessScore)}
                    {s.publishedAt && (
                      <span style={{ fontSize: 10, color: "#4b5563" }}>{formatDate(s.publishedAt)}</span>
                    )}
                  </div>
                  <div style={{ fontSize: 12, fontWeight: 700, color: "#1f2937", lineHeight: 1.4, marginBottom: 2 }}>
                    {s.title}
                  </div>
                  <div style={{ fontSize: 10, color: "#4b5563", fontFamily: "ui-monospace, SFMono-Regular, monospace", marginBottom: 6 }}>
                    /{s.slug}
                  </div>
                  {(() => {
                    const liveUrl = buildLiveUrl(publication, s.slug);
                    if (!liveUrl) return null;
                    return (
                      <div style={{ display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 6 }}>
                        <LinkChip href={liveUrl} label="Live site" color="#4b5563" />
                      </div>
                    );
                  })()}
                  {s.relevanceReason && (
                    <div style={{ fontSize: 11, color: "#1f2937", marginBottom: 6, lineHeight: 1.45 }}>
                      <span style={{ fontWeight: 700, color: "#4b5563" }}>Why it fits:</span>{" "}
                      <span style={{ fontStyle: "italic" }}>{s.relevanceReason}</span>
                    </div>
                  )}
                  {s.anchorQuote && (
                    <div
                      style={{
                        marginTop: 4,
                        padding: "6px 9px",
                        background: "rgba(0,0,0,0.025)",
                        borderRadius: 6,
                        borderLeft: "2px solid #cbd5e1",
                        fontSize: 11,
                        color: "#1f2937",
                        lineHeight: 1.5,
                      }}
                    >
                      <div style={{ fontSize: 9, fontWeight: 700, color: "#4b5563", textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: 3 }}>
                        Where to link from - paragraph {s.anchorParagraph}
                      </div>
                      <div style={{ fontStyle: "italic" }}>"{s.anchorQuote}"</div>
                      {s.anchorReason && (
                        <div style={{ fontSize: 10, color: "#4b5563", marginTop: 3, lineHeight: 1.45 }}>
                          {s.anchorReason}
                        </div>
                      )}
                    </div>
                  )}
                </div>
                <div style={{ flexShrink: 0 }}>
                  <FeedbackButton
                    suggestionType="internal_link"
                    suggestionText={s.title}
                    publication={publication}
                    documentId={documentId}
                  />
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
